### ISSUE TITLE
How to get date and build number of the IP2Location binfile(s)?

### ISSUE THREAD

**Issue by lenovo-me** [chrislim2888/ip2location#1]
Is there something like geoiplookup's -v option?

**Comment by chrislim2888** [comment]
The csv inside the tar was the old version. You could download the csv file again and build it with perl script inside. The download link: http://lite.ip2location.com.

For the version, you may get it from the IP2Location object -> databaseday, databasemonth and databaseyear.

**Comment by lenovo-me** [comment]
Thanks.
