### ISSUE TITLE
Low and High field

### ISSUE THREAD

**Issue by pexnet** [chrislim2888/ip2location#2]
Hi,

Would it be possible to have the start and and of the IP range for the searched IP in the IP2LocationRecord. A have a use for this since I need to calculate the CIDR or NET for hits I get.

I would suggest that rec.ip is the IP you searched for rec.ip_low is the start and rec.ip_high  is the end of the range for the searched IP.

pex

**Comment by chrislim2888** [comment]
This library is deprecated. Please use this https://github.com/chrislim2888/IP2Location-C-Library
